<a href="https://colab.research.google.com/github/daljit3/DFE5/blob/main/Py_00_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# list, set, dictionary, tuple
# list  [ ]-> read etc. ORDERED. INDEXED.
# set { }-> unique values only, UNORDERED. UNINDEXED.
# dictionary { key: value pairs} -> unique keys only, UNORDERED, INDEXED
# tuple ( ) -> ORDERED, INDEXED, READ ONLY 

In [1]:
# numpy gives you statistical libraries to work with individual columns!

a = [ 1, 2, 3, "pikachu", False]
print(a)

[1, 2, 3, 'pikachu', False]


In [ ]:
import numpy as np
b = np.array(a)
print(b)

['1' '2' '3' 'pikachu' 'False']


In [ ]:
b.mean()

TypeError: ignored

In [ ]:
a = [ 1, 2, 3, 42, False, 99]
print(a)

[1, 2, 3, 42, False, 99]


In [ ]:
b = np.array(a)
print(b)

[ 1  2  3 42  0 99]


In [ ]:
b.mean()

24.5

In [ ]:
b.std()

36.463452021624796

In [ ]:
z_scored_a = (b - b.mean())/ b.std()
z_scored_a

array([-0.64448094, -0.61705622, -0.5896315 ,  0.47993262, -0.67190567,
        2.04314172])

In [ ]:
print(np.reshape(b, (2,3)))
# possible shapes-> 6X1, 3X2, 1X6, 2 X 3




[[ 1  2  3]
 [42  0 99]]


In [ ]:
print(np.reshape(b, (6,1)))
# possible shapes-> 6X1, 3X2, 1X6, 2 X 3


[[ 1]
 [ 2]
 [ 3]
 [42]
 [ 0]
 [99]]


In [ ]:
print(np.reshape(b, (1,6)))

[[ 1  2  3 42  0 99]]


In [ ]:
# expected outcome-> an array containing another array containing 6 rows with 1 column
print(np.reshape(b, (1,6,1)))

[[[ 1]
  [ 2]
  [ 3]
  [42]
  [ 0]
  [99]]]
